- hosts: localhost
  tasks:
  - name: install git
    yum: name=git state=latest
    become_method: sudo
    become: yes 
  - name: clone petclinic 
    git: repo=https://github.com/ColonelLanda/spring-petclinic.git  dest=/home/ec2-user/work/petclinic update=no
  - name: clone examples
    git: repo=https://github.com/ColonelLanda/examples.git  dest=/home/ec2-user/work/examples update=no
  - name: create maven dir 
    file: path=~/maven state=directory mode=0755
  - name: unzip artifactory
    unarchive: src=http://apache.spd.co.il/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip dest=~/maven copy=no remote_src=yes creates=~/maven/apache-maven-3.3.9/README.txt
  - name: Adding M2 home env 
    lineinfile: dest=~/.bashrc line='export M2_HOME=~/maven/apache-maven-3.3.9' insertafter='EOF' regexp='export M2_HOME' state=present
  - name: Adding M2 env
    lineinfile: dest=~/.bashrc line='export M2=${M2_HOME}/bin' insertafter='EOF' regexp='export M2=' state=present
  - name: Adding the path in the bashrc files
    lineinfile: dest=~/.bashrc line='export PATH=$PATH:${M2}' insertafter='EOF' regexp='export PATH=\$PATH:\${M2}' state=present
  - name: Source the bashrc file
    shell: source ~/.bashrc
  #- name: set m2 home
